### PR TITLE
Remove unnecessary spread operator

### LINKED ISSUE #11: TypeError: Invalid attempt to spread non-iterable instance
I recently pulled this in to avoid using jQuery with cocoon. It's been great so far, but I'm starting to see this error in our Rollbar error tracker.

```
TypeError: Invalid attempt to spread non-iterable instance
1
File "webpack:///./node_modules/@kollegorna/cocoon-vanilla-js/index.js" line 3 col 39 in _nonIterableSpread
function _nonIterableSpread() { throw new TypeError("Invalid attempt to spread non-iterable insta...
2
File "webpack:///./node_modules/@kollegorna/cocoon-vanilla-js/index.js" line 1 col 95 in _toConsumableArray
function _toConsumableArray(arr) { return _arrayWithoutHoles(arr) || _iterableToArray(arr) || _no...
3
File "webpack:///./node_modules/@kollegorna/cocoon-vanilla-js/index.js" line 178 col 3 in hideFields
_toConsumableArray(document.querySelectorAll('.remove_fields.existing.destroyed')).forEach(func...
```

I believe that's coming from [this line](https://github.com/kollegorna/cocoon-vanilla-js/blob/master/index.js#L160):
```
[...document.querySelectorAll('.remove_fields.existing.destroyed')].forEach((btn) => {
```
I found a similar issue with a couple suggested fixes [here](https://github.com/babel/babel/issues/10509#issuecomment-537189235). I think the one that would work best is changing that line to:
```
[...document.querySelectorAll('.remove_fields.existing.destroyed').values()].forEach((btn) => {
```
but I'm also curious why you're doing the spread into an array to begin with. It seems like you could just chain the `.forEach` onto the `querySelectorAll`.

Anyhow, I can probably create a PR for this at some point, but I'm going to test it first and see if that fixes the issue.

### PR DESCRIPTION
**Pull request by dkniffin**
Fixes #11

### CODE REVIEW

**Comment by dkniffin** [comment]
@osvaldasvalutis Would you mind taking a look at this and merging it? Thanks!

**Comment by osvaldasvalutis** [comment]
@dkniffin the spread operator here converts NodeList to Array which allows to run forEach on older browsers (e.g. IE).

**Comment by dkniffin** [comment]
@osvaldasvalutis Ah, ok. I'll switch to `Array.from`. Will that be okay?

**Comment by osvaldasvalutis** [comment]
@dkniffin what's the reasoning behind that?

**Comment by dkniffin** [comment]
@osvaldasvalutis I described the issue over on #11, but in summary, the spread operator combined with the `querySelectorAll` intermittently has issues on some browsers (the ones we're seeing reports for are Chrome 84 & 85 on Windows, but it's hard to reproduce). I would expect Babel to resolve any issue like that, but it seems it doesn't. There's a similar issue here: https://github.com/babel/babel/issues/10509

**Comment by osvaldasvalutis** [comment]
@dkniffin 👌  https://github.com/kollegorna/cocoon-vanilla-js/releases/tag/v1.0.7

**Pull request merged**
