### PR TITLE
Bugfix to 'link_to_remove_association' button works well with HTML tags inside it, not just plain text

### PR DESCRIPTION
**Pull request by pedrofurtado**
@osvaldasvalutis 

Sometimes the `link_to_remove_association` markup may have some HTML inside, such as `<i>` tags with font-awesome and so on:

```html
<a class="remove_fields dynamic" href="#">
  <i class="fa fa-trash"></i>
  Remove
</a>
```

The `click` event could be fired in `<i>` tag instead of `<a>`, so getting the `parentNode` fix this scenario 👍

### CODE REVIEW

**Comment by pedrofurtado** [comment]
@marciojg @willradi

**Comment by pedrofurtado** [comment]
@osvaldasvalutis 🤝 🎉

**Comment by pedrofurtado** [comment]
@jnylen

**Comment by pedrofurtado** [comment]
@osvaldasvalutis @jnylen  🤝 🎉

**Comment by pedrofurtado** [comment]
Any news? @osvaldasvalutis @jnylen 👍

**Comment by pedrofurtado** [comment]
@jnylen @osvaldasvalutis I look forward to seeing this reviewed asap 👍 🎉

**Comment by pedrofurtado** [comment]
@jnylen @osvaldasvalutis I look forward to seeing this reviewed asap 👍 🎉

**Comment by pedrofurtado** [comment]
@jnylen @osvaldasvalutis 👀

**Comment by pedrofurtado** [comment]
@jnylen @osvaldasvalutis 👀

**Comment by pedrofurtado** [comment]
@jnylen @osvaldasvalutis 👀

**Comment by pedrofurtado** [comment]
@jnylen @osvaldasvalutis 👀👀

**Comment by osvaldasvalutis** [comment]
@pedrofurtado firing event on `<a>` is a semantic way of doing this kind of thing. You can workaround this by firing a custom event on `<i>` if `click` was fired `<a>`. Unfortunately we cannot accept this change as it's too subjective.

**Pull request closed without merging**
